---
title: "R Notebook"
output: html_notebook
---

# Jackknife then impute version 
# Dependencies

```{r, message=FALSE}
library(mice)
library(MASS)
library(furrr)
library(purrr)
library(tidyverse)
library(parallel)
library(latex2exp)
library(reshape2)
library(miceFast)
library(tictoc)

number_of_imps <- 10

number_of_its <- 5

options(future.rng.onMisuse = 'ignore')
```

# Data Simulation

## Defining data simulation function

```{r}
data_generator <- function(sample_size, seed, prop, desired_data){
  set.seed(seed)
  cor_mat <- matrix(c(1, 0.5, 0.5, 
                      0.5, 1, 0.5, 
                      0.5, 0.5, 1), nrow = 3, ncol = 3)
  
  mean_vec <- c(1, 1, 1)
  
  covariates <- as.data.frame(mvrnorm(sample_size, mu = mean_vec, Sigma = cor_mat))
  
  outcome_variable <- 0 + 
    2*covariates$V1 + 
    5*covariates$V2 +  
    8*covariates$V3 +
    rnorm(sample_size, 0, abs(covariates$V2))
  
  data_complete <- cbind(outcome_variable, covariates)
  
  data_w_missing <- 
    suppressWarnings(
      ampute(data_complete, prop = prop, mech = "MAR", patterns = c(0, 1, 1, 1))$amp
    )
  return(get(desired_data))
  
}
```

## Creating data for simulation

```{r}
set.seed(971423)
N = 1e4
sample_size = 50
seed = 1:N
prop = 0.3
desired_data = "data_w_missing"

# Create list of data frames with missing 
plan(multisession)

list_of_sim_data <- 
  future_map(seed, ~data_generator(sample_size, .x, prop, desired_data))

# Obtains one of the data frames to be used for small prototyping. 
df_w_mis <- list_of_sim_data[[10]]

# Function for drop-d-jackknife
choose.int <- function(x, n, k) {
  if(n <= k) return(rep(TRUE, k))
  u <- choose(n-1, k-1)
  pick <- x < u
  if (pick) y <- choose.int(x, n-1, k-1) else y <- choose.int(x-u, n-1, k)
  return(c(pick, y))
}
```

# Estimator Prototype 3
```{r}
jackknife_prototype_3 <- function(df_w_mis){
  
  n_sub_samples <- 100
  
  n = nrow(df_w_mis); k = 30
  
  length_sample_vec <- choose(n, k)
  
  if (length_sample_vec > 1e15) {
    length_sample_vec = 1e15
  } else {
    length_sample_vec = length_sample_vec
  }
  
  sample <- 
    sapply(sample.int(length_sample_vec, n_sub_samples, replace = FALSE)-1,
           choose.int, n=n, k=k)
  
  drop_d_subsamples <- map(1:ncol(sample),
                           ~df_w_mis[sample[,.x],])
  
  imputations <- replicate(n = 2,  map(drop_d_subsamples, ~.x %>%
                                         mutate(., outcome_imputed = fill_NA_N(
                                           x = .,
                                           model = "pmm", 
                                           posit_y = 1, 
                                           posit_x = c(2:4), 
                                           k = 1
                                         )) %>%
                                         select(-"outcome_variable") %>%
                                         as.matrix()), simplify = FALSE)
  
  imputations <- lapply(rapply(imputations, enquote, how="unlist"), eval)
  
  pseudo_estimates <- 
    vapply(imputations,
           function(x) .lm.fit(x = x[,1:3], y = x[,4])$coefficients[1], numeric(1))
  
  # Trimming the pseudo_estimate_vector 
  p95 <- quantile(pseudo_estimates, 0.95)
  p05 <- quantile(pseudo_estimates, 0.05)
  pseudo_estimates_trimmed <- 
    pseudo_estimates[which(pseudo_estimates <= p95 & pseudo_estimates >= p05)]
  

  jackknife_point_estimate <- mean.default(pseudo_estimates_trimmed)
  
  LB <- quantile(pseudo_estimates_trimmed, 0.025)
  UB <- quantile(pseudo_estimates_trimmed, 0.975)
  
  return(data.frame("UB" = UB, 
                    "LB" = LB, 
                    "point_estimate" = jackknife_point_estimate) %>%
           remove_rownames())

  
}
```

# Small Monte Carlo for Jackknife Estimator

```{r, eval = TRUE}
plan(multisession)

jackknife_var_estimates <- future_map_dfr(list_of_sim_data, jackknife_prototype_3)
```

# Small Monte Carlo for Rubin's Rules

```{r, eval = TRUE}
plan(multisession)

rubin_var_estimates <- 
  future_map_dfr(list_of_sim_data, 
                 ~mice(.x, seed = 123, print = FALSE, method = "pmm",
                       m = number_of_imps, maxit = number_of_its) %>%
                   mice::complete("long") %>%
                   group_by(.imp) %>%
                   do(model = lm(outcome_variable ~ V1 + V2 + V3, data = .)) %>%
                   as.list() %>%
                   .[[-1]] %>%
                   pool() %>%
                   summary(conf.int = TRUE) %>%
                   as.data.frame() %>%
                   dplyr::filter(term == "V1") %>%
                   dplyr::select(c(estimate, "2.5 %", "97.5 %")) %>%
                   dplyr::rename(point_estimate_rub = estimate, 
                                 LB_rub = "2.5 %", 
                                 UB_rub = "97.5 %")) 


```


```{r}

write.csv(cbind(rubin_var_estimates, jackknife_var_estimates), "jackk_and_rub_res.csv")
```


# Bootstrap simulation code
```{r}
library(bootImpute)

boot_analyzer <- function(df_w_mis){
  boot_impute <- bootMice(df_w_mis, nBoot = 200, nImp = 2, nCores = 1, seed = 123, print = FALSE)
  boot_impute_mat <- lapply(boot_impute, as.matrix)
  
  point_estimates <- vapply(boot_impute_mat, function(x) .lm.fit(x = x[,2:4], y = x[,1])$coefficients[1], numeric(1))
  LB <- quantile(point_estimates, 0.025)
  UB <- quantile(point_estimates, 0.975)
  
  return(data.frame("UB_boot" = UB, 
                    "LB_boot" = LB, 
                    "point_estimate_boot" = mean(point_estimates)) %>%
           remove_rownames())
}
```


# MC for bootimpute 
```{r}
plan(multisession)

boot_estimates <- future_map_dfr(list_of_sim_data, boot_analyzer)
```






# Organizing Results

```{r, eval = TRUE}
combined_results <- cbind(true_var = 2, rubin_var_estimates, jackknife_var_estimates, boot_estimates) 

rubin_width <- combined_results$UB_rub - combined_results$LB_rub

jackknife_width <- combined_results$UB - combined_results$LB

boot_width <- combined_results$UB_boot - combined_results$LB_boot

combined_results <- cbind(combined_results, rubin_width, jackknife_width, boot_width)
```

# Analysis of Results

```{r, eval = TRUE}
# Jackknife coverage probability
round((sum(combined_results$true_var < combined_results$UB & combined_results$true_var > combined_results$LB) / nrow(combined_results))*100,2)

# Coverage: 
# Jackknife -> 96 
# Boot -> 70
# Rubin -> 88

reshape2::melt(combined_results[c("point_estimate_rub", "point_estimate", "point_estimate_boot")]) %>%
  ggplot(data = .,
         aes(x = value, fill = variable, color = variable)) + 
  geom_density(aes(y = ..density..), alpha = 0.25) + 
  theme(axis.title.y = element_blank(), 
        panel.spacing=unit(1.5,"lines")) + 
  theme_bw() + 
  theme(axis.title.y = element_blank(), 
        panel.spacing=unit(1.5,"lines"), 
        strip.text = element_text(
          size = 9)) + 
  labs(
    x = latex2exp::TeX("$\\widehat{\\beta_1}")
  ) 

ggplot(combined_results, aes(x = c(1:nrow(combined_results)))) + 
  geom_point(aes(y = point_estimate, color = "red")) +
  geom_point(aes(y = 2, alpha = 0.1)) + 
  geom_errorbar(aes(ymin = LB, ymax = UB, alpha = 0.01)) + 
  coord_flip() + 
  theme_bw() + 
  labs(
    x = latex2exp::TeX("$i^{th} dataset"), 
    y = latex2exp::TeX("$\\widehat{\\sigma^2}")
  ) + 
  theme(legend.position="none") + 
  geom_hline(yintercept = combined_results$true_var)

combined_results %>%
  dplyr::select(rubin_width, jackknife_width, boot_width) %>%
  reshape2::melt() %>%
  ggplot(data = .,
         aes(x = value, fill = variable, color = variable)) + 
  geom_density(aes(y = ..density..), alpha = 0.25)

sum(rubin_width & boot_width > jackknife_width)/N * 100
```









