---
title: "Old Estimator Code"
output: html_notebook
---
      
# Dependencies

```{r, message=FALSE}
library(mice)
library(MASS)
library(furrr)
library(purrr)
library(tidyverse)
library(parallel)

number_of_imps <- 2

number_of_its <- 1

options(future.rng.onMisuse = 'ignore')
```

# Data Simulation

## Defining data simulation function

```{r}
data_generator <- function(sample_size, seed, prop, desired_data){
  set.seed(seed)
  cor_mat <- matrix(c(1, 0.5, 0.5, 
                      0.5, 1, 0.5, 
                      0.5, 0.5, 1), nrow = 3, ncol = 3)
  
  mean_vec <- c(1, 1, 1)
  
  covariates <- as.data.frame(mvrnorm(sample_size, mu = mean_vec, Sigma = cor_mat))
  
  outcome_variable <- 4 + 
    2*covariates$V1 + 
    5*covariates$V2 +  
    8*covariates$V3 +
    rnorm(sample_size, 0, 5)
  
  data_complete <- cbind(outcome_variable, covariates)
  
  data_w_missing <- 
    suppressWarnings(
      ampute(data_complete, prop = prop, mech = "MAR", patterns = c(0, 1, 1, 1))$amp
    )
  
  return(get(desired_data))
}

```

## Creating data for simulation

```{r, eval = TRUE}
set.seed(971423)
N = 100
sample_size = 100
seed = 1:N
prop = 0.3
desired_data = "data_w_missing"

# Create list of data frames with missing 
plan(multisession)

list_of_sim_data <- 
  future_map(seed, ~data_generator(sample_size, .x, prop, desired_data))

# Obtains one of the data frames to be used for small prototyping. 
df_w_mis <- list_of_sim_data[[10]]

# Generates uncongenial imputation matrix to be used later. 
uncon_pred_mat <- make.predictorMatrix(df_w_mis)

uncon_pred_mat[,4] <- 0
```

# Estimator Code

```{r}
choose.int <- function(x, n, k) {
  if(n <= k) return(rep(TRUE, k))
  u <- choose(n-1, k-1)
  pick <- x < u
  if (pick) y <- choose.int(x, n-1, k-1) else y <- choose.int(x-u, n-1, k)
  return(c(pick, y))
}
# n is the sample size of the full datasets (n = 1000 for us)
# k is the # of observations we would like to keep from n = 1000 
# The value inside sapply is the # of subsamples we would like. 
n <- 100; k <- 50 ; n_sub_samples <- 1e3

non_mice_analyzer <- function(non_mice_objects){
  lm(formula = outcome_variable ~ V1 + V2 + V3, data = non_mice_objects) %>%
    summary() %>%
    broom::tidy() %>%
    dplyr::filter(term == "V1") %>%
    dplyr::select(estimate) %>%
    unlist()
}

imp_fun <- function(to_be_imputed){
  mice(
    to_be_imputed,
    seed = 123,
    m = number_of_imps,
    method = "pmm",
    print = FALSE,
    maxit = number_of_its,
    predictorMatrix = uncon_pred_mat
  )
}

jackknife_estimator <- function(df_w_mis){
  
  length_sample_vec <- choose(n, k)
  
  if (choose(n, k) > 1e15) {
    length_sample_vec = 1e15
  } else {
    length_sample_vec = choose(n, k)
  }
  
  # Column is index for what to include/exclude 
  
  # If choose(n,k) is a big number (~1e15), code fails. 
  sample <- 
    sapply(sample.int(length_sample_vec, n_sub_samples, replace = FALSE)-1,
           choose.int, n=n, k=k)
  
   imputations <- 
    mice(df_w_mis, m = number_of_imps, maxit = number_of_its, method = "pmm", print = FALSE,
         predictorMatrix = uncon_pred_mat) %>%
    complete("long")
   
   
  
  drop_d_subsamples <- map(1:ncol(sample),
                           ~imputations[sample[,.x],])

  non_mice_res <- map(drop_d_subsamples, non_mice_analyzer)
  
  analysis_vector <- non_mice_res %>%
    do.call(rbind, .) %>%
    as.vector()
  
  point_estimate_jackknife <- mean(analysis_vector)
  
  # Quantile CI
  UB <- quantile(analysis_vector, 0.975)
  LB <- quantile(analysis_vector, 0.025)
  
  return(data.frame("point_estimate" = point_estimate_jackknife, 
                   "UB" = UB, 
                   "LB" = LB) %>% tibble::remove_rownames())
  
}
```

# Small Monte Carlo for Jackknife Estimator

```{r}
plan(multisession)

jackknife_var_est <- future_map(list_of_sim_data[1:2], jackknife_estimator)

jackknife_var_estimates <- do.call(rbind, jackknife_var_est) %>%
  as.data.frame()
```

# Small Monte Carlo for Rubin's Rules

```{r, eval = TRUE}
plan(multisession)

rubin_var_estimates <- future_map(list_of_sim_data, 
                                  ~mice(.x, seed = 123, print = FALSE, method = "pmm",
                                        m = number_of_imps, maxit = number_of_its,  predictorMatrix = uncon_pred_mat) %>%
    mice::complete("long") %>%
    group_by(.imp) %>%
    do(model = lm(outcome_variable ~ V1 + V2 + V3, data = .)) %>%
    as.list() %>%
    .[[-1]] %>%
    pool() %>%
    summary(conf.int = TRUE) %>%
    as.data.frame() %>%
    dplyr::filter(term == "V1") %>%
    dplyr::select(c(estimate, "2.5 %", "97.5 %")) %>%
    dplyr::rename(point_estimate_rub = estimate, 
                  LB_rub = "2.5 %", 
                  UB_rub = "97.5 %"))

rubin_var_estimates <- do.call(rbind, rubin_var_estimates) %>%
  as.data.frame()

# Rubin's coverage
round((sum(2 < rubin_var_estimates$UB_rub & 2 > rubin_var_estimates$LB_rub) / nrow(rubin_var_estimates))*100,2)
```

# Organizing Results

```{r}
combined_results <- cbind(true_var = 2, rubin_var_estimates, jackknife_var_estimates) 

rubin_width <- combined_results$UB_rub - combined_results$LB_rub

jackknife_width <- combined_results$UB - combined_results$LB

combined_results <- cbind(combined_results, rubin_width, jackknife_width)

# % of samples for which the rubin CI is wider than the jackknife one. 
sum(combined_results$rubin_width > combined_results$jackknife_width) / N * 100
```

# Analysis of Results

```{r}
# Jackknife coverage probability
round((sum(combined_results$true_var < combined_results$UB & combined_results$true_var > combined_results$LB) / nrow(combined_results))*100,2)

reshape2::melt(combined_results[c("point_estimate_rub", "point_estimate")]) %>%
  ggplot(data = .,
         aes(x = value, fill = variable, color = variable)) + 
  geom_density(aes(y = ..density..), alpha = 0.25) + 
  theme(axis.title.y = element_blank(), 
        panel.spacing=unit(1.5,"lines")) + 
  theme_bw() + 
  theme(axis.title.y = element_blank(), 
        panel.spacing=unit(1.5,"lines"), 
        strip.text = element_text(
          size = 9)) + 
  xlab("Beta_hat_1")

combined_results %>%
  mutate("jackknife_bias" = point_estimate - 2, 
         "rubin_bias" = point_estimate_rub - 2) %>%
  dplyr::select("jackknife_bias", "rubin_bias") %>%
  reshape2::melt() %>%
  ggplot(data = .,
         aes(x = value, fill = variable, color = variable)) + 
  geom_density(aes(y = ..density..), alpha = 0.25) + 
  theme(axis.title.y = element_blank(), 
        panel.spacing=unit(1.5,"lines")) + 
  theme_bw() + 
  theme(axis.title.y = element_blank(), 
        panel.spacing=unit(1.5,"lines"), 
        strip.text = element_text(
          size = 9)) + 
  xlab("Bias of the Jackknife Estimator")

ggplot(combined_results, aes(x = c(1:nrow(combined_results)))) + 
      geom_point(aes(y = point_estimate, color = "red")) +
      geom_point(aes(y = 2, alpha = 0.1)) + 
      geom_errorbar(aes(ymin = LB, ymax = UB, alpha = 1)) + 
      coord_flip() + 
      theme_bw() + 
      labs(
        x = latex2exp::TeX("$i^{th} dataset"), 
        y = latex2exp::TeX("$\\widehat{\\sigma^2}")
      ) + 
      theme(legend.position="none") + 
      geom_hline(yintercept = combined_results$true_var)
```